<a href="https://colab.research.google.com/github/MOHAMED-TAH00N/Deep-Learning-Tasks/blob/main/Self_Attention_Scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
sentence = "What are the symptoms of diabetes"
tokens   = sentence.split()
print(f"Tokens: {tokens}")

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes']


In [8]:
np.random.seed(42)
d_model = 8
d_k     = 4

In [9]:
X = np.random.randn(len(tokens), d_model)

In [10]:
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)

In [11]:
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

scores = Q @ K.T / np.sqrt(d_k)

In [12]:
def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / e.sum(axis=-1, keepdims=True)
attention_weights = softmax(scores)
output = attention_weights @ V


In [14]:

print("\n Raw Attention Scores (QKᵀ / √d_k) ")
print(np.round(scores, 3))

print("\n Attention Weights after Softmax ")
print(np.round(attention_weights, 3))

print("\n Self-Attention Output (weighted V) ")
print(np.round(output, 3))


 Raw Attention Scores (QKᵀ / √d_k) 
[[ -2.004   0.147  -9.267  15.636   0.998   2.071]
 [  5.695  -6.304   2.761 -11.857 -10.394  -4.06 ]
 [ -2.543   6.595   7.438  -7.684  17.113   2.249]
 [  4.895  -6.335  -4.546   1.983 -12.964  -3.087]
 [  4.339  -4.977   1.144  -6.548 -10.411  -3.24 ]
 [  4.323  -6.995  -3.21   -0.421 -16.406  -3.433]]

 Attention Weights after Softmax 
[[0.    0.    0.    1.    0.    0.   ]
 [0.949 0.    0.051 0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.   ]
 [0.948 0.    0.    0.052 0.    0.   ]
 [0.96  0.    0.039 0.    0.    0.   ]
 [0.99  0.    0.001 0.009 0.    0.   ]]

 Self-Attention Output (weighted V) 
[[ 0.416  3.178 -4.023  1.909]
 [ 0.492  4.002 -0.164 -3.637]
 [ 3.157 -2.568  1.238 -2.613]
 [ 0.594  4.557 -0.419 -3.604]
 [ 0.517  4.141 -0.177 -3.694]
 [ 0.601  4.614 -0.256 -3.851]]


In [15]:
print("\n Top attended token per word ")
for i, token in enumerate(tokens):
    top_j = np.argmax(attention_weights[i])
    print(f"  '{token}' attends most to '{tokens[top_j]}'",
          f"(weight={attention_weights[i, top_j]:.3f})")


 Top attended token per word 
  'What' attends most to 'symptoms' (weight=1.000)
  'are' attends most to 'What' (weight=0.949)
  'the' attends most to 'of' (weight=1.000)
  'symptoms' attends most to 'What' (weight=0.948)
  'of' attends most to 'What' (weight=0.960)
  'diabetes' attends most to 'What' (weight=0.990)
